import React from 'react'

import "./Automation.css"

const Automation = () => {
  return (
    <div className='automation'>
      <h2 className='automation-title'>How Does Home Automation Work?</h2>
        <p>It is hard to explain how Home-Automation works because there isn’t one universally accepted protocol. The technology varies from country, company, and type of automation. Often, because the Home-Automation market is so lucrative and fast-paced, companies will withhold new developments.          
            <br></br>The first industry standard for home Automation was X10. X10 helps devices connect to each other primarily through power line wiring, radio frequency, and wireless-based protocols. Today Zigbee, Z-Wave, and Insteon are also leading protocols for Home Automation. These new industry standards rely more heavily on modern wireless technology, like mesh-networking. All of these systems are very complicated. Simply put, they use electricity, radio waves and wireless technology to send messages to and from devices.</p>       
      <h2 className='automation-title'>App Based</h2>
        <p>App-based Smart-Home technology uses your home network to communicate with the Cloud. Cloud technology is a vital part of the Internet of Things, and both have grown very popular in the last few years. Most app based smart devices work by connecting your Home-Automation devices to your home network via Wi-Fi. Those devices connect to a severer somewhere, which you then access through apps on your smart device.
            Once you have created a personalized account with these apps you can coordinate with your Smart Home devices. This way the company knows which device goes with which app user.  As long you and your smart home devices are connected to the Internet, you can communicate back and forth with most of these cloud-based Home-Automation devices from anywhere.
            Some app-based home automation technology connects to your smart device directly through Bluetooth. Like cloud-based home-automation, you still need to create a personal account on the app. Unlike cloud-based apps though, you need to be in the vicinity of these home-automation devices for them to work.</p>
      <h2 className='automation-title'>Smart Home Basics</h2>
      <p>
        <span className='begin'>Smart Speakers:</span> It is reported that 39 Million Americans have a smart speaker in their home. It is no surprise, considering all the things they are capable of. Smart speakers can do so much more than play music, though they do an excellent job of that. They can search the internet, tell you the weather, give you a news debriefing, work as a personal assistant, and can act as a central control hub for your entire Smart-Home system.With the right smart speakers, you can control almost every aspect of your home with just your voice. Ask Alexa who is at the front door, use Siri to turn off the light you left on upstairs, and turn the heat down with Google. If you are looking to use your smart speaker as a Home-Automation hub, you need to double check that the devices you buy are compatible with your speaker as not all are.
        <br></br><span className='begin'>Smart TVs:</span> Smart TVs are great because you can watch basically anything you want, whenever you want, whether you have cable or not. A smart TV usually refers to the TV itself, but in this case, it is an umbrella statement for all IoT video streaming devices. There are tons of options these days when it comes to streaming TV. You can get a literal smart TV, that streams Netflix, Hulu, Amazon etc. straight from the unit itself, or you can get a system to pair with your normal TV. Many of these devices can be paired with your Smart Speakers and Central-Control hub, making your home even smarter.
        <br></br><span className='begin'>Smart Thermostats:</span> With smart thermostats, you can monitor your HVAC from wherever you are. You can also set them on a schedule so that energy isn’t wasted when no one is home. Some smart thermostats have a sensor option that automatically changes the temperature when they sense it is needed.
        <br></br><span className='begin'>Smart Plugs:</span> Smart plugs can convert an object into a smarter version of itself. Just plug them into your normal outlets, and then whatever is being powered by them can easily be turned on and off from your smart device.
        <br></br><span className='begin'>Light Automation:</span> When it comes to light automation there are two options. The first is installing smart light switches. Smart light switches not only can be controlled by an app, but many give you a variety of lighting choices, like dimming. The second smart lighting option is smart bulbs. Like smart plugs, smart bulbs enhance regular lights into smart ones. Switch out your old bulbs for smart ones, and you will be able to automate your lighting. So which is a better choice? Smart switches are the more affordable option but often involve complicated installations. Smart bulbs offer more lighting options, like dimming or soft light, but are more expensive because they require the purchase of a translator hub to work with your smart devices.
        <br></br><span className='begin'>Video Door Bells:</span> Video doorbells not only sense, and alert you when someone is at the front door, but can also show you video footage of who is there, and can use intercom technology to talk to your visitor. No longer do you have to yell “who’s there?” or “come in” from across the house. You can see from your smart device, or even ask your smart speaker to show you.
        <br></br><span className='begin'>Robot Vacuums:</span> Accessibility to a robot maid may be pretty far off, but a robot vacuum is the next best thing. They can be controlled from your smart devices, including your smart speakers. As if having a robot vacuum wasn’t enough, some of these vacuums come with their own artificial intelligence (AI) like your smart speakers, and a few can even stream pictures and video straight to your smart device.
      </p>
    </div>
  )
}

export default Automation
